import { RendererService } from './renderer.service';
import { BufferGeometry, DataTexture, Scene } from 'three';
import { GPUComputationRenderer, Variable } from 'three/examples/jsm/misc/GPUComputationRenderer';
export declare class Sketch {
    private renderer;
    currentShape: any;
    scene: Scene;
    isRunning: boolean;
    gpuCompute: GPUComputationRenderer;
    WIDTH: number;
    dtPosition1: DataTexture;
    dtPosition2: DataTexture;
    positionVariable: Variable;
    material: any;
    maxDistance: number;
    frequency: number;
    amplitude: number;
    faceTexture: DataTexture;
    sphereTexture: DataTexture;
    boxTexture: DataTexture;
    normalizedTime: number;
    initTexture: DataTexture;
    current: any;
    private geoFace;
    private currentTexture;
    constructor(renderer: RendererService);
    addMesh(): Promise<void>;
    addSphere(): void;
    addFace(): Promise<void>;
    initGpuCompute(): Promise<void>;
    createTexture(gpuCompute: GPUComputationRenderer, geometry: BufferGeometry): DataTexture;
    update(time: number): void;
    fillPositionTexture(dtPosition: DataTexture, geometry: any): void;
    loadObj(url: string): Promise<any>;
    morth(): void;
    onSphere(): void;
    onCube(): void;
    onFace(): void;
}
